"""仕入データ修正

Revision ID: 969afecf979c
Revises: 8e40a57e32c0
Create Date: 2023-02-24 13:04:14.965041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969afecf979c'
down_revision = '8e40a57e32c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('仕入れデータ', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('仕入れデータ', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
