"""empty message

Revision ID: 9900b9d1c2f9
Revises: 
Create Date: 2023-01-20 14:48:46.569742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9900b9d1c2f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('仕入データ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Integer(), nullable=False),
    sa.Column('purchase_category', sa.Integer(), nullable=True),
    sa.Column('purchase_slip_number', sa.Integer(), nullable=True),
    sa.Column('supplement_category', sa.String(), nullable=True),
    sa.Column('supplier_code', sa.Integer(), nullable=True),
    sa.Column('supplier_kana', sa.String(), nullable=True),
    sa.Column('goods_factory_code', sa.String(), nullable=True),
    sa.Column('goods_factory_kana', sa.String(), nullable=True),
    sa.Column('parent_goods_code', sa.Integer(), nullable=True),
    sa.Column('parent_goods_kana', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('仕入先コードマスタ',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('伝票区分マスタ',
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category')
    )
    op.create_table('出荷データ（九州）',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipping_slip_number', sa.String(), nullable=True),
    sa.Column('shipping_slip_row', sa.Integer(), nullable=True),
    sa.Column('shipping_date', sa.Integer(), nullable=True),
    sa.Column('shipping_category', sa.Integer(), nullable=True),
    sa.Column('shipping_campany_code', sa.Integer(), nullable=True),
    sa.Column('fare_category', sa.Integer(), nullable=True),
    sa.Column('consign_category', sa.Integer(), nullable=True),
    sa.Column('instruction_date', sa.Integer(), nullable=True),
    sa.Column('customer_code', sa.Integer(), nullable=True),
    sa.Column('customer_kana', sa.String(), nullable=True),
    sa.Column('customer_manager_code', sa.Integer(), nullable=True),
    sa.Column('buyer_code', sa.Integer(), nullable=True),
    sa.Column('destination_code', sa.Integer(), nullable=True),
    sa.Column('destination_kana', sa.String(), nullable=True),
    sa.Column('goods_sales_code', sa.Integer(), nullable=True),
    sa.Column('goods_sales_kana', sa.String(), nullable=True),
    sa.Column('goods_sales_grade', sa.Integer(), nullable=True),
    sa.Column('parts_number', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('back_order_category', sa.Integer(), nullable=True),
    sa.Column('back_order_quantity', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('input_day', sa.Integer(), nullable=True),
    sa.Column('input_hour', sa.Integer(), nullable=True),
    sa.Column('input_minute', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('出荷データ（本社）',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipping_slip_number', sa.String(), nullable=True),
    sa.Column('shipping_slip_row', sa.Integer(), nullable=True),
    sa.Column('shipping_date', sa.Integer(), nullable=True),
    sa.Column('shipping_category', sa.Integer(), nullable=True),
    sa.Column('shipping_campany_code', sa.Integer(), nullable=True),
    sa.Column('fare_category', sa.Integer(), nullable=True),
    sa.Column('consign_category', sa.Integer(), nullable=True),
    sa.Column('instruction_date', sa.Integer(), nullable=True),
    sa.Column('customer_code', sa.Integer(), nullable=True),
    sa.Column('customer_kana', sa.String(), nullable=True),
    sa.Column('customer_manager_code', sa.Integer(), nullable=True),
    sa.Column('buyer_code', sa.Integer(), nullable=True),
    sa.Column('destination_code', sa.Integer(), nullable=True),
    sa.Column('destination_kana', sa.String(), nullable=True),
    sa.Column('goods_sales_code', sa.Integer(), nullable=True),
    sa.Column('goods_sales_kana', sa.String(), nullable=True),
    sa.Column('goods_sales_grade', sa.Integer(), nullable=True),
    sa.Column('parts_number', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('back_order_category', sa.Integer(), nullable=True),
    sa.Column('back_order_quantity', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('input_day', sa.Integer(), nullable=True),
    sa.Column('input_hour', sa.Integer(), nullable=True),
    sa.Column('input_minute', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('出荷データ（長野）',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipping_slip_number', sa.String(), nullable=True),
    sa.Column('shipping_slip_row', sa.Integer(), nullable=True),
    sa.Column('shipping_date', sa.Integer(), nullable=True),
    sa.Column('shipping_category', sa.Integer(), nullable=True),
    sa.Column('shipping_campany_code', sa.Integer(), nullable=True),
    sa.Column('fare_category', sa.Integer(), nullable=True),
    sa.Column('consign_category', sa.Integer(), nullable=True),
    sa.Column('instruction_date', sa.Integer(), nullable=True),
    sa.Column('customer_code', sa.Integer(), nullable=True),
    sa.Column('customer_kana', sa.String(), nullable=True),
    sa.Column('customer_manager_code', sa.Integer(), nullable=True),
    sa.Column('buyer_code', sa.Integer(), nullable=True),
    sa.Column('destination_code', sa.Integer(), nullable=True),
    sa.Column('destination_kana', sa.String(), nullable=True),
    sa.Column('goods_sales_code', sa.Integer(), nullable=True),
    sa.Column('goods_sales_kana', sa.String(), nullable=True),
    sa.Column('goods_sales_grade', sa.Integer(), nullable=True),
    sa.Column('parts_number', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('back_order_category', sa.Integer(), nullable=True),
    sa.Column('back_order_quantity', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('input_day', sa.Integer(), nullable=True),
    sa.Column('input_hour', sa.Integer(), nullable=True),
    sa.Column('input_minute', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('品目コードマスタ（営業）',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('kana', sa.String(), nullable=True),
    sa.Column('parts_number', sa.String(), nullable=True),
    sa.Column('wight', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('unit_price_grade2', sa.Integer(), nullable=True),
    sa.Column('unit_price_past', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('cost_grade2', sa.Integer(), nullable=True),
    sa.Column('abolition_category', sa.String(), nullable=True),
    sa.Column('alternative_code', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('品目コードマスタ（工場）',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('kana', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('specification', sa.String(), nullable=True),
    sa.Column('diagram', sa.String(), nullable=True),
    sa.Column('parts_number', sa.String(), nullable=True),
    sa.Column('supplier_code', sa.Integer(), nullable=True),
    sa.Column('include_code', sa.Integer(), nullable=True),
    sa.Column('material_unit_price', sa.Float(), nullable=True),
    sa.Column('processing_unit_price', sa.Float(), nullable=True),
    sa.Column('scan_category', sa.Integer(), nullable=True),
    sa.Column('change_date', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('売上データ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('block_row', sa.Integer(), nullable=True),
    sa.Column('shipping_slip_number', sa.String(), nullable=True),
    sa.Column('shipping_date', sa.Integer(), nullable=True),
    sa.Column('shipping_category', sa.Integer(), nullable=True),
    sa.Column('shipping_campany_code', sa.Integer(), nullable=True),
    sa.Column('fare_category', sa.Integer(), nullable=True),
    sa.Column('consign_category', sa.Integer(), nullable=True),
    sa.Column('customer_code', sa.Integer(), nullable=True),
    sa.Column('customer_kana', sa.String(), nullable=True),
    sa.Column('customer_manager_code', sa.Integer(), nullable=True),
    sa.Column('buyer_code', sa.Integer(), nullable=True),
    sa.Column('destination_code', sa.Integer(), nullable=True),
    sa.Column('destination_kana', sa.String(), nullable=True),
    sa.Column('goods_sales_code', sa.Integer(), nullable=True),
    sa.Column('goods_sales_kana', sa.String(), nullable=True),
    sa.Column('goods_sales_grade', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('委託区分マスタ',
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category')
    )
    op.create_table('得意先コードマスタ',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('kana', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('less_rate', sa.Integer(), nullable=True),
    sa.Column('closing_date', sa.Integer(), nullable=True),
    sa.Column('manager_code', sa.Integer(), nullable=True),
    sa.Column('prefecture_code', sa.Integer(), nullable=True),
    sa.Column('post_code', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('得意先担当者コードマスタ',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('県コードマスタ',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('送荷先コードマスタ',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('kana', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('prefecture_code', sa.Integer(), nullable=True),
    sa.Column('post_code', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('flg', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('運賃扱い区分マスタ',
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category')
    )
    op.create_table('運送会社コードマスタ',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('運送会社コードマスタ')
    op.drop_table('運賃扱い区分マスタ')
    op.drop_table('送荷先コードマスタ')
    op.drop_table('県コードマスタ')
    op.drop_table('得意先担当者コードマスタ')
    op.drop_table('得意先コードマスタ')
    op.drop_table('委託区分マスタ')
    op.drop_table('売上データ')
    op.drop_table('品目コードマスタ（工場）')
    op.drop_table('品目コードマスタ（営業）')
    op.drop_table('出荷データ（長野）')
    op.drop_table('出荷データ（本社）')
    op.drop_table('出荷データ（九州）')
    op.drop_table('伝票区分マスタ')
    op.drop_table('仕入先コードマスタ')
    op.drop_table('仕入データ')
    # ### end Alembic commands ###
