"""仕入データ修正

Revision ID: f9cc42adb776
Revises: 969afecf979c
Create Date: 2023-02-24 13:33:30.356753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cc42adb776'
down_revision = '969afecf979c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('仕入れデータ', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('仕入れデータ', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
